baseurl: "online-street-photography-course"

name: "Free Online Street Photography Course"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

gems:
  - "jekyll-redirect-from"